name: Copilot Dependabot Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-analysis:
    if: github.event.pull_request.user.login == 'dependabot[bot]'    
    uses: austenstone/copilot-cli-actions/.github/workflows/copilot-dependabot-update.yml@main
